---
title: ""
format:
  html:
    toc: false
    page-layout: full
    css: styles.css
---

<h1 class="page-title">
Experiência Profissional
</h1>

:::::::::::: experience-container
::::: experience-item
::: exp-left
### Pesquisador I/ Analista de Confiabilidade

<p class="exp-org">

<i>Senai CIMATEC</i>

</p>

<ul class="exp-desc">
  <li>Desenvolvimento e aplicação de metodologias avançadas de Análise de Confiabilidade em projetos de PD\&I para o setor de Petróleo e Gás, com foco na identificação e mitigação de falhas em sistemas complexos.</li>
  <li>Suporte na prospecção de novos projetos e condução de reuniões técnicas com stakeholders.</li>
  <li>Elaboração de relatórios técnicos e apresentação de resultados para equipes multidisciplinares e clientes.</li>
  <li>Programação de aplicações e scripts para automação e análise de dados de confiabilidade.</li>
</ul>
:::

::: exp-right
Maio 2024 – Março 2025
:::
:::::

::::: experience-item
::: exp-left
### Cientista de dados

<p class="exp-org">

<i>Conselho Nacional de Desenvolvimento Científico e Tecnológico</i>

</p>

<ul class="exp-desc">
  <li>Pesquisa e implementação de algoritmos de agrupamento (clustering) para dados categóricos em ambiente Big Data.</li>
  <li>Desenvolvimento de modelos preditivos, extração de features (feature engineering) e análises descritivas.</li>
  <li>Limpeza, reestruturação e manipulação de bases de dados de alta dimensão (Big Data).</li>
</ul>
:::

::: exp-right
Outubro 2021 – Junho 2022
:::
:::::

::::: experience-item
::: exp-left
### Estatístico/Bolsista de Iniciação científica

<p class="exp-org">

<i> Instituto de Saúde Coletiva (UFBA)/ Universidade Federal da Bahia </i>

</p>

<ul class="exp-desc">
  <li>Gerenciamento do pipeline de dados, incluindo montagem, limpeza, extração e merge de bases de questionários.</li>
  <li>Aplicação de métodos estatísticos para análise dos dados do projeto "Desenvolvimento Infantil na Comunidade".</li>
  <li>Criação de relatórios para acompanhamento do progresso da coleta e monitoramento da qualidade dos dados.</li>
  <li>Apoio na elaboração de materiais para seminários, congressos e participação na escrita de artigos científicos.</li>
</ul>
:::

::: exp-right
Dezembro 2017 – Janeiro 2021
:::
:::::
::::::::::::
